name: Renovate Dependencies

on:
  # # Schedule the workflow to run every Monday at 08:00 UTC.
  # # See: https://crontab.guru/
  # schedule:
  #   - cron: '0 8 * * 1'

  # # Run whenever code is pushed to the main branch
  # # TODO: does this update existing PRs without creating new ones?
  # push:
  #   branches:
  #     - main

  # issues:
  #   types: [edited]

  # issue_comment:
  #   types: [created]

  # Allow manual triggering from the GitHub Actions UI
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run Renovate in dry-run mode"
        required: false
        default: false
        type: boolean

jobs:
  renovate:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@4.2.2

      - name: Run Renovate 🔍
        uses: renovatebot/github-action@v41.0.17 # v41.0.17
        with:
          configurationFile: .github/renovate.json5
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          renovate-version: 39.215.2@sha256:644608e6c6e0956856b392c01bd2e5b71fb6fa2162a4f7e932de930743f92cf4
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_DRY_RUN: ${{ (github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.dry-run == 'true')) && 'full' || null }}
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
